# action.yml
name: 'Aws EKS Helm Chart Deployer'
description: 'Deploy any Helm Chart to Aws EKS Cluster using GitHub Actions'
inputs:
  aws-access-key-id:
    description: 'Aws Access Key ID'
    required: true
    default: ''
  aws-secret-access-key:
    description: 'Aws Secret Access Key'
    required: true
    default: ''
  aws-cluster-name:
    description: 'Aws Cluster name'
    required: true
    default: ''
  aws-default-region:
    description: 'Aws Default Region'
    required: false
    default: 'us-west-2'
  helm-chart-folder:
    description: 'Helm chart'
    required: true
    default: ''
  helm-release:
    description: 'Helm release name or folder where the chart is'
    required: true
    default: ''
  k8s-namespace:
    description: 'k8s namespace'
    required: true
    default: ''
  helm-parameters:
    description: 'Helm deployment parameters using the Helm --set format. Example: param1=value1,param2:value2'
    required: false
    default: ''
  helm-deploy-timeout:
    description: "Set timeout to wait for the deployment of the helm chart. Example: 30s, 60s, 300s, 5m, 5m0s."
    required: false
    default: ''
  app-version:
    description: "Set the app version"
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-default-region }}
    - ${{ inputs.aws-cluster-name }}
    - ${{ inputs.helm-chart-folder }}
    - ${{ inputs.helm-release }}
    - ${{ inputs.k8s-namespace }}
    - ${{ inputs.helm-parameters }}
    - ${{ inputs.helm-deploy-timeout }}
    - ${{ inputs.app-version }}