# action.yml
name: 'Aws KubeConfig Generator'
description: 'Generates a KubeConfig file and leaves in the folder you mounted to /project'
inputs:
  aws-access-key-id:
    description: 'Aws Access Key ID'
    required: true
    default: ''
  aws-secret-access-key:
    description: 'Aws Secret Access Key'
    required: true
    default: ''
  aws-cluster-name:
    description: 'Aws Cluster name'
    required: true
    default: ''
  aws-default-region:
    description: 'Aws Default Region'
    required: false
    default: 'us-west-2'
  helm-chart-folder:
    description: 'Helm chart'
    required: true
    default: ''
  helm-release:
    description: 'Helm release name'
    required: true
    default: ''
  k8s-namespace:
    description: 'k8s namespace'
    required: true
    default: ''
outputs:
  result:
    description: 'result of helm deployment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-default-region }}
    - ${{ inputs.aws-cluster-name }}
    - ${{ inputs.helm-chart-folder }}
    - ${{ inputs.helm-release }}
    - ${{ inputs.k8s-namespace }}